# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

  # black: Python Formatter
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3.7

  # flake8: Python PEP8 Compliance
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
      additional_dependencies: [
        'flake8-bugbear==20.1.4'
      ]
      args: [--config=setup.cfg]

  # General Text + YAML Lint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: paper/*
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: mixed-line-ending
        exclude: paper/*
        args: [--fix=lf]
      - id: detect-private-key

  # Markdown lint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.23.1
    hooks:
      - id: markdownlint
        args: [--config=.github/markdown_lint.yaml, --ignore=paper/]
